spring.application.name=Todo
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/todoapp_db
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration (Hibern auto-detects dialect)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8122
